### ISSUE TITLE
New user account causes NameError

### ISSUE THREAD

**Issue by mglenc** [leibowitz/django-azure-ad-auth#5]
Hi,
There is a bug in `azure_ad_auth/backends.py` in `create_user` method. Trying to login with new account (that does not exist in Django) causes `NameError` when calling `self.username_generator(email)` in line 95. Field `email` should be taken from `user_kwargs` dictionary.

**Comment by leibowitz** [comment]
Should be fixed in master - sorry for the delay, I didn't have notifications turned on 😞
