### ISSUE TITLE
ImportError: cannot import name 'urlencode'

### ISSUE THREAD

**Issue by somendrameena** [leibowitz/django-azure-ad-auth#6]
I am using Python 3.5.2 in my Django app. When I try to login, it gives me this error

> Exception Value: `cannot import name 'urlencode'`
> Exception location: .../site-packages/azure_ad_auth/utils.py in <module>, line 8

**Comment by felixschul** [comment]
There is an update for Python 3 compatibility, but it is not published to Pypi yet. You can install the latest version like `pip install 
https://github.com/leibowitz/django-azure-ad-auth/archive/dev_1.5.0.zip` or add `
https://github.com/leibowitz/django-azure-ad-auth/archive/dev_1.5.0.zip` to your requirements.txt

**Comment by leibowitz** [comment]
@felixschul is right in the sense that python 3 support exists in master since https://github.com/leibowitz/django-azure-ad-auth/pull/2

You can use this fork (from master) or from release, as per @felixschul suggestion
